electronic_shop/electronic_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('techway.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api_electronic_shop.urls'))
]

electronic_shop/techway/urls.py
from django.urls import path
from . import views

app_name = 'TechWay'
urlpatterns = [
    path('home/', views.main_view, name='home'),
    path('catalog/', views.catalog_view, name='catalog'),
    path('favorite/', views.favorite_view, name='favorite'),
    path('backet/', views.backet_view, name='backet'),
    path('personal_account/', views.personal_account_view, name='personal_account'),
    path('authorization/', views.authorization_view, name='auth'),
    path('registration/', views.registration_view, name='reg'),
    path('product/<int:product_id>', views.product_view, name='product_window'),
    path('admin_panel/', views.admin_panel_view, name='admin_panel'),
    path('personal_account_admin/', views.personal_account_admin_view, name='personal_account_admin'),
    path('update_list_product/', views.update_product_list),
    path('add_to_basket/<int:product_id>', views.add_to_basket),
    path('delete_item_basket/', views.delete_item_basket),
    path('change_data_basket/', views.change_data_basket),
    path('get_list_data_admin/', views.get_list_data_admin),
    path('update_status_order/', views.update_status_order),
    path('create_report_admin_panel/', views.create_report_admin_panel),
    path('delete_admin_panel/', views.delete_admin_panel),
    path('add_change_data/', views.add_change_data),
    path('add_change_data_page/', views.add_change_data_view, name='add_change'),
    path('history_order/', views.history_order_view, name='history_order'),
    path('create_check_history_order/', views.create_check_history_order),
    path('add_favorite_item/', views.add_favorite_item),
    path('delete_favorite_item/', views.delete_favorite_item),
    path('password_recovery/', views.password_recovery_view, name='password_recovery'),
    path('change_password/<str:hash>/', views.change_password_view, name='change_password'),
]

electronic_shop/techway/views.py
import requests, base64
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.core.mail import EmailMultiAlternatives
from python_moduls.pdf_files import *
from python_moduls.modul import *
from django.conf import settings
from django.templatetags.static import static
from email.mime.image import MIMEImage
from email.mime.application import MIMEApplication

URL_API = 'http://127.0.0.1:8000/api/'
URL_BACK = 'http://127.0.0.1:8000/'

def send_to_mail(to_mail, title_mail, template_mail, dict_data={}, file_name_pdf=None, pdf=None):
    html_content = render_to_string(f'techway\\{template_mail}', context=dict_data)

    msg = EmailMultiAlternatives(
        title_mail,
        '',
        settings.EMAIL_HOST_USER,
        [to_mail],
        headers={'test' : 'test'}
    )
    msg.attach_alternative(html_content, "text/html")

    photo_path = f'{os.path.dirname(__file__)}{static("techway/images/logo.png")}'
    
    with open(photo_path, 'rb') as f:
        image = MIMEImage(f.read())

    image.add_header('Content-ID', '<logo>')
    
    if file_name_pdf and pdf:
        with open(pdf, 'rb') as file:
            content = MIMEApplication(file.read(), 'pdf', filename = file_name_pdf)

        content.add_header('Content-Disposition', 'attachment', filename=file_name_pdf)
        content.add_header('Content-ID', '<check>')

        msg.attach(content)

    msg.attach(image)

    try:
        msg.send()
    except Exception as e:
        return False

    return True

def check_to_admin(id_user: int) -> bool:
    position = requests.get(f'{URL_API}auth_reg_user/{id_user}').json()['position']
    return position != 'Клиент'

def update_product_list(request: HttpRequest) -> JsonResponse:
    if request.method == 'GET':
        id_user = f'iduser={request.session["id_user"]}' if 'id_user' in request.session else ''
        sort = f'sort={request.GET["sort"]}' if 'sort' in request.GET else ''
        subcategory = f'subcategory={request.GET["subcategory"]}' if 'subcategory' in request.GET else ''
        search = f'search={request.GET["search"]}' if 'search' in request.GET else ''
        number_page = f'number_page={request.GET["number_page"]}' if 'number_page' in request.GET else ''
        data_to_api = '&'.join([i for i in [id_user, sort, subcategory, search, number_page] if i != ''])
        response = requests.get(f'{URL_API}product_list/?{data_to_api}').json()
        product_list = response['list_data']
        count_page = response['count_page']

        render_page = render(request, 'techway\\product_previews_list.html', context={'product_list' : product_list, 'count_page' : count_page})
        return JsonResponse({
            'result' : True,
            'product_list_page' : render_page.content.decode("utf-8")
        })
    
def main_view(request: HttpRequest) -> HttpResponse:
    '''
    Представление для обработки главной страницы.
    '''

    if 'mail_user_recovery_password' in request.session:
        request.session.pop('mail_user_recovery_password')

    if 'hash_to_reset_password' in request.session:
        request.session.pop('hash_to_reset_password')

    if 'id_user' in request.session and check_to_admin(request.session['id_user']):
        return redirect('TechWay:admin_panel')
    
    if request.method == 'GET':
        id_user = f'iduser={request.session["id_user"]}' if 'id_user' in request.session else ''
        subcateory = ''
        categories = ''
        search = f'search={request.GET["search"]}' if 'search' in request.GET else ''
        sort = f'sort={request.GET["sort"]}' if 'sort' in request.GET else ''
        number_page = f'number_page={request.GET["number_page"]}' if 'number_page' in request.GET else ''
        if 'subcategory' in request.session:
            subcateory = f'subcategory={request.session["subcategory"]}'
            categories = [*requests.get(f'{URL_API}categoty_section/?subcategory={request.session["subcategory"]}').json().values(), request.session["subcategory"]]
            request.session.pop('subcategory')

        data_to_api = '&'.join([i for i in [id_user, subcateory, search, sort, number_page] if i != ''])
        response = requests.get(f'{URL_API}product_list/?{data_to_api}').json()
        product_list = response['list_data']
        count_page = response['count_page']
        all_product_items = response['all_product_items']

        dict_data = {
            'product_list' : product_list, 
            'number_page' : request.GET["number_page"] if 'number_page' in request.GET else 1, 
            'count_page' : count_page, 
            'categories' : categories, 
            'search' : request.GET["search"] if 'search' in request.GET else '',
            'all_product_items' : all_product_items,
            'sort' : request.GET['sort'] if 'sort' in request.GET else '',
        }

        return render(request, 'techway\\main_window.html', context=dict_data)

def catalog_view(request: HttpRequest) -> HttpResponse:
    '''
    Представление для обработки страницы с каталогом.
    '''
    if 'id_user' in request.session and check_to_admin(request.session['id_user']):
        return redirect('TechWay:admin_panel')
    
    if request.method == 'GET':
        if 'subcategory' in request.GET:
            request.session['subcategory'] = request.GET['subcategory'] 
            return redirect('TechWay:home')

        elif 'category' in request.GET:
            all_categories = requests.get(f'{URL_API}subcategory_list_catalog/?category={request.GET["category"]}').json()
            select_categories = ['Каталог', request.GET['section'], request.GET['category']]
            return render(request, 'techway\\catalog.html', context={'all_categories' : all_categories, 'select_categories' : select_categories})
            
        elif 'section' in request.GET:
            all_categories = requests.get(f'{URL_API}category_list_catalog/?section={request.GET["section"]}').json()
            select_categories = ['Каталог', request.GET['section']]
            return render(request, 'techway\\catalog.html', context={'all_categories' : all_categories, 'select_categories' : select_categories})
        
        else:
            all_categories = requests.get(f'{URL_API}section_list/').json()
            select_categories = []

        return render(request, 'techway\\catalog.html', context={'all_categories' : all_categories, 'select_categories' : select_categories})

def favorite_view(request: HttpRequest) -> HttpResponse:
    '''
    Представление для обработки страницы с избранным.
    '''

    if 'id_user' not in request.session:
        return redirect('TechWay:home')

    if check_to_admin(request.session['id_user']):
        return redirect('TechWay:admin_panel')

    if request.method == 'GET':
        return render(request, 'techway\\favorite.html', context={
            'favorites': requests.get(f'{URL_API}favorite_action/?id_user={request.session["id_user"]}').json()})

def backet_view(request: HttpRequest) -> HttpResponse:
    '''
    Представление для обработки страницы с корзиной.
    '''
    
    if 'id_user' not in request.session or check_to_admin(request.session['id_user']):
        return redirect('TechWay:home')

    if request.method == 'GET':
        order_product = requests.get(f'{URL_API}basket_list/?id_user={request.session["id_user"]}')
        shop_list = requests.get(f'{URL_API}shop_list/')
        payment_method_list = [
            {'id_payment_method' : 1, 'method' : 'Наличными'},
            {'id_payment_method' : 2, 'method' : 'Картой'}
        ]
        return render(request, 'techway\\backet.html', context={
            'order_product': [] if order_product.status_code == 204 else order_product.json(),
            'shop_list' : shop_list.json(),
            'payment_method_list' : payment_method_list 
            })
    
    if request.method == 'POST':
        payment_method_list = [
            {'id_payment_method' : 1, 'method' : 'Наличными'},
            {'id_payment_method' : 2, 'method' : 'Картой'}
        ]

        method = ''
        for i in payment_method_list:
            if i['id_payment_method'] == int(request.POST['select_payment_method']):
                method = i['method']
                break

        json_data = {
            'id_user' : request.session['id_user'],
            'status' : 'Оформлен',
            'payment_method' : method,
            'id_shop' : request.POST['select_shop'],
        }

        receive_order = requests.post(f'{URL_API}update_data_order/', data=json_data)

        if receive_order.status_code == 400:
            order_product = requests.get(f'{URL_API}basket_list/?id_user={request.session["id_user"]}')
            shop_list = requests.get(f'{URL_API}shop_list/')
            payment_method_list = [
                {'id_payment_method' : 1, 'method' : 'Наличными'},
                {'id_payment_method' : 2, 'method' : 'Картой'}
            ]
            return render(request, 'techway\\backet.html', context={
                'order_product': [] if order_product.status_code == 204 else order_product.json(),
                'shop_list' : shop_list.json(),
                'payment_method_list' : payment_method_list,
                **receive_order.json()
            })

        receive_order = receive_order.json()
        response = requests.get(f'{URL_API}receive_cleared_products/?id_order={receive_order["idorder"]}').json()
        shop = requests.get(f'{URL_API}shop_list/?idshop={request.POST["select_shop"]}').json()[0]['addres']
        
        path_file_check = create_check_order(receive_order['idorder'], shop, method, response['date_ordering'], response['list_product'])

        email_user = requests.get(f'{URL_API}auth_reg_user/{request.session["id_user"]}').json()['mail']

electronic_shop/techway/templates/techway/add_change_employee.html
{% load static %}
<form class="box_margin form_add_change_data" action="" method="post">
    {% csrf_token %}
    <div class="box_data">
        <label for="id_employee">Номер сотрудника: </label>
        <input name="id_employee" type="text" value="{{ iduser }}" readonly>
    </div>
    <div class="box_data">
        <label for="mail_employee">Почта: </label>
        <input type="text" name="mail_employee" value="{{ mail }}" pattern="^[A-Za-z0-9]{3,}[@][A-Za-z]{3,}[.][A-Za-z]+$" maxlength="255" {% if mail %} disabled {% endif %}>
    </div>
    
    <div class="box_data">
        <label for="password_employee">Пароль: </label>
        <div class="box_input_password">
            <input type="password" name="password_employee" value="{{ password }}" id="password_employee_id" pattern="^[A-Za-z\d]{5,}$" maxlength="100" {% if password %} disabled {% endif %} required>
            <img src="{% static 'techway/images/show.png' %}" width="25" height="25" alt="" id="visibility_password_add_img" {% if not password %} onclick="visibility_password('visibility_password_add_img', 'password_employee_id')" {% endif %}>
        </div>
    </div>
    <div class="box_data">
        <label for="select_position">Должность: </label>
        <select name="select_position" id="">
            {% for i in position_list %}
            <option value="{{ i }}" {% if i == position %}selected{% endif %}>{{ i }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="box_data">
        <label for="select_status">Статус: </label>
        <select name="select_status" id="">
            {% for i in status_list %}
            <option value="{{ i }}" {% if i == status %}selected{% endif %}>{{ i }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="box_data">
        <label for="lastname_employee">Фамилия: </label>
        <input name="lastname_employee" type="text" pattern="^[а-яёА-ЯЁ]{3,}$" maxlength="45" value="{{ lastname }}" required>
    </div>

    <div class="box_data">
        <label for="firstname_employee">Имя: </label>
        <input name="firstname_employee" type="text" pattern="^[а-яёА-ЯЁ]{3,}$" maxlength="45" value="{{ firstname }}" required>
    </div>

    <div class="box_data">
        <label for="midlename_employee">Отчество(при наличие): </label>
        <input name="midlename_employee" type="text" pattern="^[а-яёА-ЯЁ]{3,}$" maxlength="45" value="{{ midlename }}">
    </div>
    
    <div class="box_data">
        <label for="birthdate_employee">Дата рождения: </label>
        <input type="date" name="birthdate_employee" value="{{ birthdate }}" required>
    </div>
    
    <div class="box_data">
        <label for="phone_number_employee">Номер телефона: </label>
        <input name="phone_number_employee" type="text" pattern="^[+][7][0-9]{10}$" required maxlength="12" value="{{ phone_number }}">
    </div>
    
    <div class="box_btn">
        <button class="add_change" type="submit">{% if iduser == -1 %}Добавить{% else %}Изменить{% endif %}</button>
    </div>
</form>

<script>
    $(document).ready(function(){
        $('input[type="date"]').attr('min', maxBirthDate());
        $('input[type="date"]').attr('max', minBirthDate());
    });
</script>

electronic_shop/techway/templates/techway/admin_page.html
{% extends 'TechWay/base_admin.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>TechWay - Админ панель</title>
        <link rel="stylesheet" href="{% static 'techway/styles/admin_panel_style.css' %}">
    {% endblock head %}
</head>
<body>
    {% block body %}
        {% if position == 'Администратор' %}
            {% include 'techway/chief_administrator_submission.html' %}
        {% else %}
            {% include 'techway/minor_administrator_introduction.html' %}
        {% endif %}
    {% endblock body %}
</body>
</html>

electronic_shop/techway/templates/techway/authorization.html
{% extends 'TechWay/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>TechWay - авторизация</title>
        <link rel="stylesheet" href="{% static 'techway/styles/authorization_style.css' %}">
    {% endblock head %}
</head>
<body>
    {% block body %}
    <div class="container main_box center_elements">
        <div class="main_box_auth">
            <h1 class="text_align_center title_text">Авторизация</h1>
            <form action="" method="post" class="box_auth" id="form_auth">
                {% csrf_token %}
                <p class="error_text" id="error_id"></p>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <label for="login_input" id="label_mail" class="label_for_input" style="display: none;">Введите почту</label>
                        <input class="input_data" type="text" name="input_mail" id="login_input" oninput="checkPlaceHolder('label_mail', 'login_input')" required pattern="^[A-Za-z0-9]{3,}[@][A-Za-z]{3,}[.][A-Za-z]+$">
                    </div>
                </div>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <label for="password_input" id="label_password" class="label_for_input" style="display: none; width: 80%;">Введите пароль</label>
                        <div class="box_password">
                            <input class="input_data" type="password" name="input_password" id="password_input" oninput="checkPlaceHolder('label_password', 'password_input')" required pattern="^[A-Za-z\d]{5,}$">
                            <img src="{% static 'techway/images/show.png' %}" alt="" id="visibility_password_img" onclick="visibility_password('visibility_password_img', 'password_input')">                        
                        </div>
                        <div class="box_link_to_reg">
                            <a class="link_to_reg" href="{% url 'TechWay:password_recovery' %}">Восстановить пароль</a>
                            <p>Нет аккаунта? <a class="link_to_reg" href="{% url 'TechWay:reg' %}">Создать</a></p>
                        </div>
                    </div>
                </div>
                <input type="submit" value="Войти" id="sign_in_btn_id" class="sign_in_btn">
            </form>
        </div>
    </div>
    <script src="{% static 'techway/scripts/index.js' %}"></script>
    <script src="{% static 'techway/scripts/auth_script.js' %}"></script>
    {% endblock body %}
</body>
</html>

electronic_shop/techway/templates/techway/catalog.html
{% extends 'TechWay/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>TechWay - каталог</title>
        <link rel="stylesheet" href="{% static 'techway/styles/catalog_style.css' %}">
    {% endblock head %}
</head>
<body>
    {% block body %}
        <div class="container main_box_category">
            {% if select_categories %}
            <div class="сatalog_item box_margin">
                <!-- <p>Каталог > Мобильные устройства > Смартфоны и гаджеты > Смартфоны</p> -->
                <p id="select_categories">{{ select_categories|join:" > " }}</p>
            </div>
            {% endif %}
            
            <h1 class="name_current_category {% if not select_categories %}box_margin{% endif %}">Каталог товаров</h1>
            
            <div class="box_all_card_category">
                {% for category in all_categories %}
                    <!-- Карточка категории -->
                    <div class="card_category">
                        <div class="box_image_category">
                            <img src="{% static 'techway/images/' %}{{ category.path_image }}" alt="">
                        </div>
                        <div class="box_text_category">
                            <p class="name_category">{{ category.name }}</p>
                        </div>
                    </div>
                    <!-- -->
                {% endfor %}
            </div>
        </div>
        <script src="{% static 'techway/scripts/catalog_script.js' %}"></script>
    {% endblock body %}
</body>
</html>

electronic_shop/techway/templates/techway/change_password.html
{% extends 'TechWay/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>TechWay - создание нового пароля</title>
        <link rel="stylesheet" href="{% static 'techway/styles/change_password_style.css' %}">
    {% endblock head %}
</head>
<body>
    {% block body %}

        <div class="container">
            <h1 class="text_align_center title_text">Создание нового пароля</h1>

            <form class="box_margin form_change_password" action="" method="post">
                {% csrf_token %}
                <p class="error_text" {% if not error %} hidden {% endif %}>{{ error }}</p>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <label for="password_input" id="label_password" class="label_for_input" style="display: none;">Введите пароль</label>
                        <div class="box_password">
                            <input class="input_data" type="password" name="input_password" id="password_input" oninput="checkPlaceHolder('label_password', 'password_input')" required pattern="^[A-Za-z\d]{5,}$" maxlength="100">
                            <img src="{% static 'techway/images/show.png' %}" alt="" id="visibility_password_img" onclick="visibility_password('visibility_password_img', 'password_input')">
                        </div>
                    </div>
                </div>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <label for="password_confirm_input" id="label_password_confirm" class="label_for_input" style="display: none;">Подтвердите пароль</label>
                        <div class="box_password">
                            <input class="input_data" type="password" name="input_password_confirm" id="password_confirm_input" oninput="checkPlaceHolder('label_password_confirm', 'password_confirm_input')" required pattern="^[A-Za-z\d]{5,}$" maxlength="100">
                            <img src="{% static 'techway/images/show.png' %}" alt="" id="visibility_password_confirm_img" onclick="visibility_password('visibility_password_confirm_img', 'password_confirm_input')">
                        </div>
                    </div>
                </div>
                <input class="update_password_btn" type="submit" value="Создать пароль">
            </form>
        </div>
    <script src="{% static 'techway/scripts/change_password_script.js' %}"></script>
    {% endblock body %}
</body>
</html>

electronic_shop/techway/templates/techway/favorite.html
{% extends 'TechWay/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>TechWay - избранное</title>
        <link rel="stylesheet" href="{% static 'techway/styles/favorite_style.css' %}">
    {% endblock head %}
</head>
<body>
    {% block body %}
    
    <div class="container main_box">
        <div class="main_box_favorite box_margin">
            <div class="box_title">
                <h1 class="title_text">Избранное</h1>
            </div>

            {% include 'TechWay/favorite_list_view.html' %}

        </div>
    </div>

    {% endblock body %}
</body>
</html>

electronic_shop/techway/templates/techway/registration.html
{% extends 'TechWay/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>TechWay - регистрация</title>
        <link rel="stylesheet" href="{% static 'techway/styles/registration_style.css' %}">
    {% endblock head %}
</head>
<body>
    {% block body %}
    <div class="container main_box center_elements">
        <div class="main_box_auth box_margin">
            <h1 class="text_align_center title_text">Регистрация</h1>
            <form action="" method="post" class="box_auth" id="form_auth">
                {% csrf_token %}
                <p class="error_text text_align_center" id="error_id">{{ dict_data.error }}</p>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <label for="login_input" id="label_mail" class="label_for_input" style="display: none;">Введите почту</label>
                        <input class="input_data" type="text" name="input_mail" id="login_input" oninput="checkPlaceHolder('label_mail', 'login_input')" required pattern="^[A-Za-z0-9]{3,}[@][A-Za-z]{3,}[.][A-Za-z]+$" maxlength="255" value="{{ dict_data.mail }}">
                    </div>
                </div>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <label for="last_name_input" id="label_last_name" class="label_for_input" style="display: none;">Введите фамилию</label>
                        <input class="input_data" type="text" name="input_last_name" id="last_name_input" oninput="checkPlaceHolder('label_last_name', 'last_name_input')" required pattern="^[а-яёА-ЯЁ]{3,}$" maxlength="45" value="{{ dict_data.lastname }}">
                    </div>
                </div>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <label for="first_name_input" id="label_first_name" class="label_for_input" style="display: none;">Введите имя</label>
                        <input class="input_data" type="text" name="input_first_name" id="first_name_input" oninput="checkPlaceHolder('label_first_name', 'first_name_input')" required pattern="^[а-яёА-ЯЁ]{3,}$" maxlength="45" value="{{ dict_data.firstname }}">
                    </div>
                </div>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <input class="input_data" type="date" name="input_birthdate" required title="Выберете дату рождения" value="{{ dict_data.birthdate }}">
                    </div>
                </div>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <label for="password_input" id="label_password" class="label_for_input" style="display: none;">Введите пароль</label>
                        <div class="box_password">
                            <input class="input_data" type="password" name="input_password" id="password_input" oninput="checkPlaceHolder('label_password', 'password_input')" required pattern="^[A-Za-z\d]{5,}$" maxlength="100" value="{{ dict_data.password }}">
                            <img src="{% static 'techway/images/show.png' %}" alt="" id="visibility_password_img" onclick="visibility_password('visibility_password_img', 'password_input')">
                        </div>
                    </div>
                </div>
                <div class="box_input_data">
                    <div class="box_input_data_final">
                        <label for="password_confirm_input" id="label_password_confirm" class="label_for_input" style="display: none;">Подтвердите пароль</label>
                            <div class="box_password">
                                <input class="input_data" type="password" name="input_password_confirm" id="password_confirm_input" oninput="checkPlaceHolder('label_password_confirm', 'password_confirm_input')" required pattern="^[A-Za-z\d]{5,}$" maxlength="100" value="{{ dict_data.password_confirm }}">
                                <img src="{% static 'techway/images/show.png' %}" alt="" id="visibility_password_confirm_img" onclick="visibility_password('visibility_password_confirm_img', 'password_confirm_input')">
                            </div>
                            <div class="box_link_to_reg">
                            <p>Есть аккаунт? <a class="link_to_reg" href="{% url 'TechWay:auth' %}">Войти</a></p>
                        </div>
                    </div>
                </div>
                <input type="submit" value="Создать" class="sign_in_btn">
            </form>
        </div>
    </div>
    <script src="{% static 'techway/scripts/index.js' %}"></script>
    <script src="{% static 'techway/scripts/reg_script.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('input[type="date"]').attr('min', maxBirthDate());
            $('input[type="date"]').attr('max', minBirthDate());
        });
    </script>
    {% endblock body %}
</body>
</html>

electronic_shop/techway/templates/techway/result_change_password.html
{% extends 'TechWay/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>TechWay - успешное создание нового пароля</title>
        <style>
            .box_content_result{
                height: 20vh;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: space-between;
            }

            .back_to_auth{
                min-height: 40px;
                min-width: 300px;
                text-decoration: none;
                border: 2px solid black;
                border-radius: 5px;
                display: flex;
                align-items: center;
                justify-content: center;
                font-size: 16px;
                color: black;
            }
            .back_to_auth:hover{
                color: rgb(0, 110, 255);
                background-color: gainsboro;
            }
            .back_to_auth:active{
                color: blue;
                background-color: gray;
                
            }
        </style>
    {% endblock head %}
</head>
<body>
    {% block body %}

        <div class="container">
            <div class="box_content_result">
                <h1 class="title_text text_align_center">Поздравляем!</h1>
                <h3 class="text_align_center">{{ result }}</h3>
                <a class="back_to_auth" href="{% url 'TechWay:auth' %}">Вернуться на страницу с авторизацией</a>
            </div>
        </div>
        
    {% endblock body %}
</body>
</html>